### ISSUE TITLE
Is supporting MIME sniffing necessary?

### ISSUE THREAD

**Issue by domenic** [dalecurtis/image-decoder-api#1]
MIME sniffing is a general source of security bugs on the platform, and we're putting a lot of effort into restricting and removing it where possible. (See e.g. CORB, X-Content-Type-Options, all modern elements requiring strict MIME type matches, ...)

I'm not sure how many of those concerns apply to this API shape; perhaps a restriction to images might make things less bad? Or, if you have the raw bytes anyway, sniffing isn't a problem?

But, I think including MIME sniffing would need some powerful motivation, so it would be good to include a section discussing why it's necessary.

**Comment by dalecurtis** [comment]
I'm not sure it's necessary, but not having it would be surprising to users I expect. I.e., we provide sniffing via img and picture today. Probably the best thing to do is follow the mime spec on sniffing. I.e., let the type be provided and require it be correct if specified, but if not sniff.

**Comment by domenic** [comment]
Well, this is a new feature, so we should err toward not carrying over legacy when possible...

**Comment by dalecurtis** [comment]
That's fair, but I don't think the reasons why have changed. We see similar discussions around the strictness of our mime type requirements for MediaSource.addSourceBuffer() -- we long wanted the container and codec explicitly, but folks ingesting 3rd party content wouldn't know the codec sometimes and thus needed another control plane or they'd embed a mp4 demuxer.

I.e., authors may not know what type of image they got (they could guess by extension probably). CDNs may even do transcoding on the fly. We see this today for .gif -> webp.

**Comment by jyasskin** [comment]
Do you see those third-parties omitting or sending incorrect `Content-Type` headers? The first-party might not know the type statically, but they should get it back from the content's server as part of the response.

It does seem possible to require the right MIME-type ["essence"](https://mimesniff.spec.whatwg.org/#mime-type-essence) without requiring extra parameters like [`addSourceBuffer()` wanted](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource/addSourceBuffer#Example) for `video/mp4`. I don't claim to know what'll be practical for developers.

**Comment by dalecurtis** [comment]
That's fair, the addSourceBuffer case is a bit different, since it requires things beyond the mime type; if the mime-type can be retrieved via the Content-Type maybe we can get away without it.

**Comment by jyasskin** [comment]
I agree with what I think you mean, but just to be technically correct: if https://developer.mozilla.org/en-US/docs/Web/API/MediaSource/addSourceBuffer#Example is correct about what Blink wanted, all of `video/mp4; codecs="avc1.42E01E, mp4a.40.2"` is the MIME type (technically the ["media type"](https://developer.mozilla.org/en-US/docs/Glossary/MIME_type)...), and it would all be transmitted in the [`Content-Type`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) header and available in the [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response/headers) to a `fetch()`. 

The `video/mp4` part is the ["essence"](https://mimesniff.spec.whatwg.org/#mime-type-essence) of the MIME type, and does seem like the part servers are more likely to get right.

**Comment by dalecurtis** [comment]
Hmm, I'm not aware of any serving sites which provide the codec information through the Content-Type; it would require they inspect the byte stream which things like apache, etc are not going to do.

**Comment by dalecurtis** [comment]
Just realized either way we'll need a ImageDecoder.canDecodeType(<mime_type>) or ImageDecoder.supports(<mime_type>) method as well then.

**Comment by dalecurtis** [comment]
Fixed in https://chromium.googlesource.com/chromium/src/+/b4f55bf20945772a314c5f3e80bd8b9fdc982119 - which removes mime sniffing in favor of an explicit type being required.
