### ISSUE TITLE
GIF frame disposal method

### ISSUE THREAD

**Issue by hugo306** [dalecurtis/image-decoder-api#2]
ImageFrame will need to expose the disposal method for meaningful GIF rendering.
Disposal is a 3 bit value. 0-3 have defined behaviors, while 4-7 do not.

Edit: Unless the frames are delivered to the consumer pre-composed. It must do right? Otherwise you also require the x,y position of the frames which differ per frame.

**Comment by dalecurtis** [comment]
Yes the frames will be delivered pre-composed in the case of GIF. I think it's too much of a burden to expect users to handle this otherwise.

**Comment by hugo306** [comment]
Which also means the frames can be written using transferFromImageBitmap at almost no cost too.
That's great, thanks.
