### ISSUE TITLE
Should we support progressive image decoding?

### ISSUE THREAD

**Issue by dalecurtis** [dalecurtis/image-decoder-api#3]
If so, how? Here's what I've gotten working in a [prototype](https://chromium-review.googlesource.com/c/chromium/src/+/2166131):

```JavaScript
interface ImageDecoder {
  // Decodes the frame at the given index. If we're still receiving data, this
  // method will wait to resolve the promise until the given |frameIndex| is
  // available or reject the promise if we receive all data or fail before
  // |frameIndex| is available.
  //
  // When |completeFramesOnly| is set to false, partial progressive frames will
  // be returned. When in this mode, decode() calls will resolve only once per
  // new partial image at |frameIndex| until the frame is complete.
  Promise<ImageFrame> decode(unsigned long frameIndex,
                             optional boolean completeFramesOnly = true);

  ...
}

dictionary ImageFrame {
  // Indicates if the decoded image is actually complete.
  required boolean complete;

  ...
}
```

This allows authors who want access to progressive decoding to call decode($frame_index) repeatedly and have the promises only resolve when a new partial image is available. The [example in the explainer](https://github.com/dalecurtis/image-decoder-api/blob/master/explainer.md#example-1-animated-gif-renderer) only needs a minor update to support progressive rendering then:

```JavaScript
function renderImage(imageFrame) {
  canvasContext.drawImage(imageFrame.image, 0, 0);
  if (imageDecoder.frameCount == 1 && imageFrame.complete)
    return;

  // Keep requesting and rendering the same frame until it's completely decoded.
  if (!imageFrame.complete)  {
    imageDecoder.decode(imageIndex, false).then(renderImage);
    return;
  }

  ...
}

function decodeImage(imageByteStream) {
  ...
  imageDecoder.decode(imageIndex, false).then(renderImage);
}
```

The downsides with this approach is that authors must cache the resulting ImageFrame object since they will not be able to access it again until the image is updated.

@padenot @sandersdan

**Comment by LeonScroggins** [comment]
FWIW, Chromium will only progressively decode the first frame. (It will decode the second frame before the third frame is available, but not until it thinks all of the data for the second frame is available.) The thinking is that showing part of a frame on top of the prior frame is not desirable. (I suppose this is less of a problem for independent frames, though.)

**Comment by dalecurtis** [comment]
Thanks I hadn't explicitly realized that. I think for most (maybe all?) codecs and formats that limitation is baked in. Maybe with the ISO-BMFF container used by AVIF you might be able to order samples weirdly, but it doesn't support progressive. Just that you can decode sample N with only the samples since the nearest key-frame before N.

**Comment by munrocket** [comment]
This is actually not a very popular technique, but it works so well that I just wonder why this is not a default feature!

**Comment by dalecurtis** [comment]
@munrocket The above solution is now available in Chrome Canary 84.0.4147.0+ behind the flag --enable-blink-features=WebCodecs if you want to try it out and see how it works for you.

**Comment by munrocket** [comment]
@dalecurtis I need to turn on this flag and then use your code snippet?

**Comment by munrocket** [comment]
Need to try it, can we also create a proposal in tc39 then?

**Comment by dalecurtis** [comment]
@munrocket You need to launch Chrome Canary from the command line with that flag, see https://www.chromium.org/developers/how-tos/run-chromium-with-flags -- I don't know what a TC39 proposal is :)

**Comment by sandersdan** [comment]
TC39 develops ECMAScript; ImageDecoder is outside of their domain (this is more WhatWG/W3C territory).

**Comment by munrocket** [comment]
I see, we can't propose this feature right now because other browser doesn't know about ImageDecoder.

> * Firefox : Positive (unofficially)

**Comment by munrocket** [comment]
Trying to find a champion from TC39 to wrap this idea in a proposal and add this to the ecmascript specification. https://es.discourse.group/t/jpeg-progressive-loading-for-webgl-webgpu/359

**Comment by munrocket** [comment]
Seems that ImageDecoder little bit similar to TextEncoder API in naming.

**Comment by munrocket** [comment]
>TC39 develops ECMAScript; ImageDecoder is outside of their domain

Ok, I get it.

**Comment by dalecurtis** [comment]
Marking as fixed since the API supports this now.

**Comment by munrocket** [comment]
@dalecurtis what about other browsers? Do you discussed this in some committee?

**Comment by dalecurtis** [comment]
We're still waiting for other browsers to review the API, so it's not guaranteed this will be in the final API, but it's in the current explainer.

**Comment by munrocket** [comment]
Can I read this type of discussions somewhere in mail-list or in some github repo? Seems this I know nothing about W3C.
