### ISSUE TITLE
ImageEncoder

### ISSUE THREAD

**Issue by rektide** [dalecurtis/image-decoder-api#7]
I recently got interested in building some small image processing tools on the web, and one missing piece that would be lovely to have would be image encoding. I've been investigating various webassembly options for encoding images, but ideally, the platform itself would let me take my bitmap images & spit out encoded images, under a variety of lossy & lossless compression setting across various codecs.

Longer term, some ImageEncoder encoding profiles might even become hardware accelerated, which could be a huge battery saver!

**Comment by dalecurtis** [comment]
Sorry this is the wrong place for this. You'll want to create a new issue in the WebCodecs repo. This repo is only for the explainer and is historical only now.
